
package UI;
import DB.DBConnector;
import OrderingSystem.SessionManager;
import UI.ArmChairsDashboard;
import UI.SofasDashboard1;
import UI.OttomanDashboard;
import UI.CustomerDashboard;
import UI.CustomerAdminDashboard;
import UI.Cart;
import UI.Orders;
import UI.OrderTracking;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author jessa
 */
public class UpholsteredFurniture extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rst;
private int customerId;
    /**
     * Creates new form UpholsteredFurniture
     */
    public UpholsteredFurniture() {
        initComponents();
        DBConnector mycon = new DBConnector();
        conn = DBConnector.getCon();
        this.customerId = SessionManager.getCustomerID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SofasLabel = new javax.swing.JLabel();
        OttomanButton = new javax.swing.JButton();
        OttomanLabel = new javax.swing.JLabel();
        ArmchairsLabel = new javax.swing.JLabel();
        SofasButton = new javax.swing.JButton();
        ArmChairsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        OrdersButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        OrderTracking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SofasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UpholsteredFurniture/475883994_1736921900500350_850297494677894551_n.jpg"))); // NOI18N
        getContentPane().add(SofasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 230, 180));

        OttomanButton.setBackground(new java.awt.Color(101, 101, 101));
        OttomanButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        OttomanButton.setForeground(new java.awt.Color(255, 255, 255));
        OttomanButton.setText("OTTOMAN");
        OttomanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OttomanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OttomanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 420, 180, 50));

        OttomanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UpholsteredFurniture/476565378_672684258416956_3133996071740475308_n.jpg"))); // NOI18N
        getContentPane().add(OttomanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, 230, 180));

        ArmchairsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UpholsteredFurniture/ArmChair.jpg"))); // NOI18N
        getContentPane().add(ArmchairsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 230, 180));

        SofasButton.setBackground(new java.awt.Color(101, 101, 101));
        SofasButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SofasButton.setForeground(new java.awt.Color(255, 255, 255));
        SofasButton.setText("SOFAS");
        SofasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SofasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SofasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 180, 50));

        ArmChairsButton.setBackground(new java.awt.Color(101, 101, 101));
        ArmChairsButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ArmChairsButton.setForeground(new java.awt.Color(255, 255, 255));
        ArmChairsButton.setText("ARM CHAIRS");
        ArmChairsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmChairsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ArmChairsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 180, 50));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DYEY EN DI'S FURNITURE HAVEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UPHOLSTERED FURNITURE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1180, 700));

        jPanel4.setBackground(new java.awt.Color(140, 122, 107));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("    HAVEN");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel16.setText("DYEY");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("EN");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 40, 30, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel18.setText("DI'S");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setText("FURNITURE");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, -1));

        HomeButton.setBackground(new java.awt.Color(101, 101, 101));
        HomeButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 50));

        OrdersButton.setBackground(new java.awt.Color(101, 101, 101));
        OrdersButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        OrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        OrdersButton.setText("Orders");
        OrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersButtonActionPerformed(evt);
            }
        });
        jPanel4.add(OrdersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 50));

        HistoryButton.setBackground(new java.awt.Color(101, 101, 101));
        HistoryButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        HistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        HistoryButton.setText("Cart");
        HistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryButtonActionPerformed(evt);
            }
        });
        jPanel4.add(HistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 50));

        LogOutButton.setBackground(new java.awt.Color(180, 100, 100));
        LogOutButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel4.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 180, 50));

        OrderTracking.setBackground(new java.awt.Color(101, 101, 101));
        OrderTracking.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        OrderTracking.setForeground(new java.awt.Color(255, 255, 255));
        OrderTracking.setText("Order Tracking");
        OrderTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderTrackingActionPerformed(evt);
            }
        });
        jPanel4.add(OrderTracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArmChairsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmChairsButtonActionPerformed
        ArmChairsDashboard obj = new ArmChairsDashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ArmChairsButtonActionPerformed

    private void SofasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SofasButtonActionPerformed
        SofasDashboard1 obj = new SofasDashboard1();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_SofasButtonActionPerformed

    private void OttomanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OttomanButtonActionPerformed
        OttomanDashboard obj = new OttomanDashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_OttomanButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        CustomerDashboard obj = new CustomerDashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void OrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Note: You can only edit order information if the status is 'Pending'.");

        Orders obj = new Orders();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_OrdersButtonActionPerformed

    private void HistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryButtonActionPerformed
        Cart obj = new Cart();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_HistoryButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed

       LocalDateTime now = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    String formattedDateTime = now.format(formatter);

    System.out.println("Customer logged out at: " + formattedDateTime);

    try {
       
        String sql = "UPDATE customerlogin SET LogOut = ? WHERE CustomerID = ? AND LogOut IS NULL ORDER BY LogIn DESC LIMIT 1";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, formattedDateTime);
        pst.setInt(2, SessionManager.getCustomerID());

        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            System.out.println("Logout time saved successfully!");
        } else {
            System.out.println("No active session found to update logout time.");
        }

        pst.close();

       
        String fetchUsernameSQL = "SELECT Username FROM customer WHERE CustomerID = ?";
        PreparedStatement fetchUsernamePst = conn.prepareStatement(fetchUsernameSQL);
        fetchUsernamePst.setInt(1, SessionManager.getCustomerID());
        ResultSet rsUsername = fetchUsernamePst.executeQuery();

        String username = "";
        if (rsUsername.next()) {
            username = rsUsername.getString("Username");
        }

        rsUsername.close();
        fetchUsernamePst.close();

       
        String sqlAudit = "INSERT INTO audit_logs (UserType, Username, ActionType, TableAffected, RecordID, ActionDetails) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pstmtAudit = conn.prepareStatement(sqlAudit);
        pstmtAudit.setString(1, "Customer");
        pstmtAudit.setString(2, username);  
        pstmtAudit.setString(3, "Logout");
        pstmtAudit.setString(4, "customer");
        pstmtAudit.setInt(5, SessionManager.getCustomerID());  
        pstmtAudit.setString(6, "Customer logged out successfully");

        pstmtAudit.executeUpdate();
        pstmtAudit.close();

        

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while saving logout time or audit log.");
    }

  
    CustomerAdminDashboard obj = new CustomerAdminDashboard();
    obj.setVisible(true);
    dispose(); 
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void OrderTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderTrackingActionPerformed
        OrderTracking obj = new OrderTracking();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_OrderTrackingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpholsteredFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpholsteredFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpholsteredFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpholsteredFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpholsteredFurniture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArmChairsButton;
    private javax.swing.JLabel ArmchairsLabel;
    private javax.swing.JButton HistoryButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton OrderTracking;
    private javax.swing.JButton OrdersButton;
    private javax.swing.JButton OttomanButton;
    private javax.swing.JLabel OttomanLabel;
    private javax.swing.JButton SofasButton;
    private javax.swing.JLabel SofasLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
